Support S2 angle for folders (not .SAFE) and Reestructure repository to cookiecutter
marujore/sentinel_angle_bands pull request #3
Opened 2021-07-05 16:49 UTC by marujore

2021-08-10 17:50 UTC, raphaelrpl requested changes

2021-08-10 17:50 UTC, raphaelrpl commented on docs/sphinx/index.rst
> +A client library in Python for generating Sentinel-2 Angle Bands[C.
There are non printable chars in this line.

2021-08-10 17:50 UTC, raphaelrpl commented on s2angs/config.py
> +    S2ANGS_SMTP_PORT = os.getenv('S2ANGS_SMTP_PORT', 587)
What are these variables? Is it valid?

2021-08-10 17:50 UTC, raphaelrpl commented on s2angs/s2_angs.py
> +    imgref = [f for f in glob.glob(imgFolder + "**/*04*.jp2", recursive=True)]
Since you are seeking for `.jp2` files, you should consider to add a validation here since it may be empty.

2021-08-11 16:16 UTC, marujore commented on s2angs/config.py
> +    S2ANGS_SMTP_PORT = os.getenv('S2ANGS_SMTP_PORT', 587)
The file has been removed

2021-08-11 16:16 UTC, marujore commented on s2angs/s2_angs.py
> +    imgref = [f for f in glob.glob(imgFolder + "**/*04*.jp2", recursive=True)]
Agree. Solved.

2021-08-11 16:17 UTC, merged